import { useEffect, useMemo, useState, type ElementType, type ReactNode } from 'react';
import { AlertTriangle, BatteryCharging, Bell, Fuel, Gauge, LogOut, MapPin, Radio, Route, Search, ShieldCheck, Thermometer, Timer, UserRound, Video } from 'lucide-react';
import type { AuthUser } from '@/lib/api';
import type { LiveDriverView } from './live-driver';
import FleetMap from './fleet-map';
import { vehicles, type Vehicle, type VehicleStatus } from '@/data/fleet';
import '@/fleet-dashboard.css';

type Props={user:AuthUser;logout:()=>void;loggingOut:boolean;logoutError:string;live:LiveDriverView};
const labels:Record<VehicleStatus,string>={critical:'Kritis',warning:'Waspada',safe:'Aman'};
function Brand(){return <a className="brand" href="/"><span className="brand-glyph">S</span><span>SELAMATE<small>FLEET COMMAND CENTER</small></span></a>}
function FleetList({selected,onSelect}:{selected:Vehicle;onSelect:(v:Vehicle)=>void}){const[filter,setFilter]=useState<'all'|VehicleStatus>('all'),[query,setQuery]=useState('');const list=useMemo(()=>vehicles.filter(v=>(filter==='all'||v.status===filter)&&(v.id.toLowerCase().includes(query.toLowerCase())||v.driver.toLowerCase().includes(query.toLowerCase()))),[filter,query]);return <aside className="fleet-panel"><div className="panel-title"><p className="eyebrow">ARMADA AKTIF</p><h2>{vehicles.length} <small>kendaraan</small></h2></div><label className="search"><Search size={15}/><input aria-label="Cari kendaraan" placeholder="Cari ID atau driver" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="filters">{(['all','critical','warning','safe'] as const).map(value=><button key={value} className={filter===value?'active':''} onClick={()=>setFilter(value)}>{value==='all'?'Semua':labels[value]}<span>{value==='all'?vehicles.length:vehicles.filter(v=>v.status===value).length}</span></button>)}</div><div className="vehicle-list">{list.map(v=><button key={v.id} className={`vehicle-row ${selected.id===v.id?'selected':''}`} onClick={()=>onSelect(v)}><i className={v.status}/><span><strong>{v.id}</strong><small>{v.driver}</small><em><MapPin size={10}/>{v.location}</em></span><b className={v.status}>{v.score}</b></button>)}</div><div className="live-foot"><span><i/>Pemantauan live</span><small>Data simulasi · 5 dtk</small></div></aside>}
function Metric({icon:Icon,label,value,tone}:{icon:ElementType;label:string;value:string;tone?:string}){return <div className="metric"><Icon size={16}/><span>{label}<strong className={tone}>{value}</strong></span></div>}
function CameraFeed({vehicle,liveCamera}:{vehicle:Vehicle;liveCamera?:ReactNode}){return <section className={`camera-feed ${vehicle.camera}`}>{liveCamera||<><div className="camera-top"><span><i/>CAM-01 · SIMULASI</span><span>1080P</span></div><div className="driver-silhouette"><div className="face-box"><span/><i/><b/></div></div><div className="scan-line"/><div className="camera-bottom"><span>{vehicle.driver}</span><span>FACE TRACKING</span></div></>}</section>}
function MonitorPanel({vehicle,live}:{vehicle:Vehicle;live:LiveDriverView}){const realCamera=(live.monitoring||live.cameraActive)?live.camera:null;return <aside className="monitor-panel"><div className="monitor-head"><div><p className="eyebrow">MONITOR KENDARAAN</p><h2>{vehicle.id}</h2><span><UserRound size={12}/>{vehicle.driver}</span></div><b className={vehicle.status}>{labels[vehicle.status]}</b></div><CameraFeed vehicle={vehicle} liveCamera={realCamera}/><div className="camera-caption"><span><Video size={14}/>{realCamera?'Kamera kabin terhubung':'Preview kamera simulasi'}</span><small>{realCamera?live.cameraStatus:'Bukan rekaman nyata'}</small></div><section className="fatigue-card"><div><span>FATIGUE RISK</span><strong className={vehicle.status}>{vehicle.fatigue}%</strong></div><div className="risk-bar"><i className={vehicle.status} style={{width:`${vehicle.fatigue}%`}}/></div><p><AlertTriangle size={14}/>{vehicle.lastEvent}</p></section><div className="metrics-grid"><Metric icon={Gauge} label="Kecepatan" value={`${vehicle.speed} km/j`}/><Metric icon={Timer} label="Durasi berkendara" value={vehicle.driveTime} tone={vehicle.status==='critical'?'critical':''}/><Metric icon={Fuel} label="Bahan bakar" value={`${vehicle.fuel}%`}/><Metric icon={Thermometer} label="Suhu mesin" value={`${vehicle.engineTemp}°C`}/><Metric icon={Radio} label="Sinyal GPS" value={`${vehicle.signal}%`}/><Metric icon={ShieldCheck} label="Sabuk pengaman" value={vehicle.seatbelt?'Terpasang':'Lepas'} tone={vehicle.seatbelt?'safe':'critical'}/></div><section className="vehicle-status"><h3>Status perjalanan</h3><div><MapPin size={15}/><span>Posisi<strong>{vehicle.location}</strong></span></div><div><Route size={15}/><span>Tujuan<strong>{vehicle.destination}</strong></span></div><div><BatteryCharging size={15}/><span>Sistem kendaraan<strong>Normal</strong></span></div></section><button className="alert-button"><Bell size={15}/>Kirim peringatan ke driver</button></aside>}
export default function FleetDashboard({user,logout,loggingOut,logoutError,live}:Props){const[selected,setSelected]=useState(vehicles[0]),[now,setNow]=useState('');useEffect(()=>{const tick=()=>setNow(new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit',second:'2-digit'}));tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[]);return <div className="command-shell"><header className="topbar"><Brand/><div className="top-meta"><span className="online"><i/>{vehicles.length} kendaraan online</span><time>{now} WIB</time><div className="user-chip"><span>{user.name}<small>{user.role}</small></span><button onClick={logout} disabled={loggingOut} aria-label="Keluar"><LogOut size={16}/></button></div></div></header>{logoutError&&<p className="fleet-error" role="alert">{logoutError}</p>}<FleetList selected={selected} onSelect={setSelected}/><main className="map-panel"><div className="map-header"><div><p className="eyebrow">LIVE MONITORING</p><h1>Peta armada operasional</h1><span>Tol Cipularang · Jawa Barat</span></div><div className="legend"><span><i className="critical"/>Kritis</span><span><i className="warning"/>Waspada</span><span><i className="safe"/>Aman</span></div></div><div className="map-wrap"><FleetMap fleet={vehicles} selected={selected} onSelect={setSelected}/><div className="route-summary"><div><span>UNIT DIPANTAU</span><strong>{selected.id}</strong></div><div><span>KECEPATAN</span><strong>{selected.speed} km/j</strong></div><div><span>RISK SCORE</span><strong className={selected.status}>{selected.score}/100</strong></div><div><span>TUJUAN</span><strong>{selected.destination}</strong></div></div></div></main><MonitorPanel vehicle={selected} live={live}/></div>}
