import React, { FormEvent, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AlertTriangle, BatteryCharging, Bell, Camera, Fuel, Gauge, LogOut, MapPin, Radio, Route, Search, ShieldCheck, Thermometer, Timer, UserRound, Video } from 'lucide-react';
import FleetMap from '@/components/fleet-map';
import { vehicles, type Vehicle, type VehicleStatus } from '@/data/fleet';
import './styles.css';

type User = { id:string; name:string; email:string; role:'Admin'|'Driver' };
const statusLabel:Record<VehicleStatus,string>={critical:'Kritis',warning:'Waspada',safe:'Aman'};

function Login({onLogin}:{onLogin:(user:User)=>void}){const[email,setEmail]=useState('driver@selamate.id'),[password,setPassword]=useState('Driver123!'),[error,setError]=useState(''),[loading,setLoading]=useState(false);async function submit(event:FormEvent){event.preventDefault();setLoading(true);setError('');try{const response=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const data=await response.json();if(!response.ok)throw new Error(data.detail||'Login gagal');onLogin(data.user)}catch(err){setError(err instanceof Error?err.message:'Login gagal')}finally{setLoading(false)}}return <main className="login-page"><section className="login-card"><Brand/><p className="eyebrow">FLEET SAFETY PLATFORM</p><h1>Masuk ke pusat kendali.</h1><p>Pantau kendaraan dan keselamatan pengemudi dalam satu layar.</p><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<p className="form-error" role="alert">{error}</p>}<button disabled={loading}>{loading?'Memeriksa…':'Masuk dashboard'}</button></form><div className="demo-credentials"><strong>Akun demo</strong><span>Driver · driver@selamate.id / Driver123!</span><span>Admin · admin@selamate.id / Admin123!</span></div></section></main>}
function Brand(){return <a className="brand" href="/"><span className="brand-glyph">S</span><span>SELAMATE<small>FLEET COMMAND CENTER</small></span></a>}
function FleetList({selected,onSelect}:{selected:Vehicle;onSelect:(v:Vehicle)=>void}){const[filter,setFilter]=useState<'all'|VehicleStatus>('all'),[query,setQuery]=useState('');const list=useMemo(()=>vehicles.filter(v=>(filter==='all'||v.status===filter)&&(v.id.toLowerCase().includes(query.toLowerCase())||v.driver.toLowerCase().includes(query.toLowerCase()))),[filter,query]);return <aside className="fleet-panel"><div className="panel-title"><p className="eyebrow">ARMADA AKTIF</p><h2>{vehicles.length} <small>kendaraan</small></h2></div><label className="search"><Search size={15}/><input aria-label="Cari kendaraan" placeholder="Cari ID atau driver" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="filters">{(['all','critical','warning','safe'] as const).map(value=><button key={value} className={filter===value?'active':''} onClick={()=>setFilter(value)}>{value==='all'?'Semua':statusLabel[value]}<span>{value==='all'?vehicles.length:vehicles.filter(v=>v.status===value).length}</span></button>)}</div><div className="vehicle-list">{list.map(v=><button key={v.id} className={`vehicle-row ${selected.id===v.id?'selected':''}`} onClick={()=>onSelect(v)}><i className={v.status}/><span><strong>{v.id}</strong><small>{v.driver}</small><em><MapPin size={10}/>{v.location}</em></span><b className={v.status}>{v.score}</b></button>)}</div><div className="live-foot"><span><i/>Pemantauan live</span><small>Data simulasi · 5 dtk</small></div></aside>}
function Metric({icon:Icon,label,value,tone}:{icon:React.ElementType;label:string;value:string;tone?:string}){return <div className="metric"><Icon size={16}/><span>{label}<strong className={tone}>{value}</strong></span></div>}
function CameraFeed({vehicle}:{vehicle:Vehicle}){return <section className={`camera-feed ${vehicle.camera}`}><div className="camera-top"><span><i/>CAM-01 · LIVE</span><span>1080P</span></div><div className="driver-silhouette"><div className="face-box"><span/><i/><b/></div></div><div className="scan-line"/><div className="camera-bottom"><span>{vehicle.driver}</span><span>FACE TRACKING</span></div></section>}
function MonitorPanel({vehicle}:{vehicle:Vehicle}){return <aside className="monitor-panel"><div className="monitor-head"><div><p className="eyebrow">MONITOR KENDARAAN</p><h2>{vehicle.id}</h2><span><UserRound size={12}/>{vehicle.driver}</span></div><b className={vehicle.status}>{statusLabel[vehicle.status]}</b></div><CameraFeed vehicle={vehicle}/><div className="camera-caption"><span><Video size={14}/>Kamera kabin aktif</span><small>Simulasi feed · bukan rekaman nyata</small></div><section className="fatigue-card"><div><span>FATIGUE RISK</span><strong className={vehicle.status}>{vehicle.fatigue}%</strong></div><div className="risk-bar"><i className={vehicle.status} style={{width:`${vehicle.fatigue}%`}}/></div><p><AlertTriangle size={14}/>{vehicle.lastEvent}</p></section><div className="metrics-grid"><Metric icon={Gauge} label="Kecepatan" value={`${vehicle.speed} km/j`}/><Metric icon={Timer} label="Durasi berkendara" value={vehicle.driveTime} tone={vehicle.status==='critical'?'critical':''}/><Metric icon={Fuel} label="Bahan bakar" value={`${vehicle.fuel}%`}/><Metric icon={Thermometer} label="Suhu mesin" value={`${vehicle.engineTemp}°C`}/><Metric icon={Radio} label="Sinyal GPS" value={`${vehicle.signal}%`}/><Metric icon={ShieldCheck} label="Sabuk pengaman" value={vehicle.seatbelt?'Terpasang':'Lepas'} tone={vehicle.seatbelt?'safe':'critical'}/></div><section className="vehicle-status"><h3>Status perjalanan</h3><div><MapPin size={15}/><span>Posisi<strong>{vehicle.location}</strong></span></div><div><Route size={15}/><span>Tujuan<strong>{vehicle.destination}</strong></span></div><div><BatteryCharging size={15}/><span>Sistem kendaraan<strong>Normal</strong></span></div></section><button className="alert-button"><Bell size={15}/>Kirim peringatan ke driver</button></aside>}
function Dashboard({user,onLogout}:{user:User;onLogout:()=>void}){const[selected,setSelected]=useState(vehicles[0]),[now,setNow]=useState('');useEffect(()=>{const tick=()=>setNow(new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit',second:'2-digit'}));tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[]);return <div className="command-shell"><header className="topbar"><Brand/><div className="top-meta"><span className="online"><i/>{vehicles.length} kendaraan online</span><time>{now} WIB</time><div className="user-chip"><span>{user.name}<small>{user.role}</small></span><button onClick={onLogout} aria-label="Keluar"><LogOut size={16}/></button></div></div></header><FleetList selected={selected} onSelect={setSelected}/><main className="map-panel"><div className="map-header"><div><p className="eyebrow">LIVE MONITORING</p><h1>Peta armada operasional</h1><span>Tol Cipularang · Jawa Barat</span></div><div className="legend"><span><i className="critical"/>Kritis</span><span><i className="warning"/>Waspada</span><span><i className="safe"/>Aman</span></div></div><div className="map-wrap"><FleetMap fleet={vehicles} selected={selected} onSelect={setSelected}/><div className="route-summary"><div><span>UNIT DIPANTAU</span><strong>{selected.id}</strong></div><div><span>KECEPATAN</span><strong>{selected.speed} km/j</strong></div><div><span>RISK SCORE</span><strong className={selected.status}>{selected.score}/100</strong></div><div><span>TUJUAN</span><strong>{selected.destination}</strong></div></div></div></main><MonitorPanel vehicle={selected}/></div>}
function App(){const[user,setUser]=useState<User|null>(null),[checking,setChecking]=useState(true);useEffect(()=>{fetch('/api/auth/me').then(async r=>{if(r.ok)setUser((await r.json()).user)}).finally(()=>setChecking(false))},[]);async function logout(){await fetch('/api/auth/logout',{method:'POST'});setUser(null)}if(checking)return <div className="splash">SELAMATE</div>;return user?<Dashboard user={user} onLogout={logout}/>:<Login onLogin={setUser}/>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
